name: react-nest-ecommerce

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_EXPOSE_PORT}:80"
  backend:
    build: ./backend
    ports:
      - "${BACKEND_EXPOSE_PORT}:3000"

networks:
  default:
    name: react-nest-ecommerce-network

volumes:
  react-nest-ecommerce-volume:
